// <auto-generated />
namespace Portal.CMS.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AvoidReservedTypeNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AvoidReservedTypeNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201703242023520_AvoidReservedTypeNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
