// <auto-generated />
namespace Portal.CMS.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StripWebsiteAddressFromUploadedContent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StripWebsiteAddressFromUploadedContent));
        
        string IMigrationMetadata.Id
        {
            get { return "201707211220449_StripWebsiteAddressFromUploadedContent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
