// <auto-generated />
namespace Portal.CMS.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Columnnamechangeforkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Columnnamechangeforkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201902061751282_Column name change for keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
